//
//  Layer.swift
//  DL4S
//
//  Created by Palle Klewitz on 12.10.19.
//  Copyright (c) 2019 - 2026 - Palle Klewitz
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation

/// A layer of a neural network that performs an arbitrary transformation on its inputs to generate its outputs.
/// To do so, it may rely on a set of parameters (weights) may be trained through optimization.
///
/// Train a layer with ``update(_:)``:
///
/// ```swift
/// var model = Sequential {
///     Dense<Float, CPU>(inputSize: 784, outputSize: 10)
///     LogSoftmax<Float, CPU>()
/// }
/// var optimizer = Adam<Float, CPU>(learningRate: 0.001)
///
/// let loss = categoricalNegativeLogLikelihood(expected: labels, actual: model(images))
/// model.update { parameters in
///     optimizer.update(&parameters, along: loss.gradients(of: parameters))
/// }
/// ```
public protocol LayerType<Inputs, Outputs, Parameter, Device>: TensorContainer {
    /// Inputs of the layer
    associatedtype Inputs

    /// Outputs of the layer
    associatedtype Outputs

    /// Performs a transformation determined by the type of the layer.
    ///
    /// The transformation may use parameters that the layer has.
    /// - Parameter inputs: Inputs of the layer
    /// - Returns: Outputs generated by transforming the inputs using the parameters of the layer.
    func callAsFunction(_ inputs: Inputs) -> Outputs
}

public extension LayerType {
    /// The tensors that an optimizer updates: all weights of the layer and its sublayers that require a gradient.
    ///
    /// The order is the traversal order of ``TensorContainer/visitTensors(_:)``. It is the same order that ``update(_:)`` uses
    /// and that ``weightPaths`` describes.
    var parameters: [Tensor<Parameter, Device>] {
        var parameters: [Tensor<Parameter, Device>] = []
        var copy = self
        var visitor = TensorVisitor<Parameter, Device>(tensors: { tensor, role, _ in
            if role == .weight, tensor.requiresGradient {
                parameters.append(tensor)
            }
        })
        copy.visitTensors(&visitor)
        return parameters
    }

    /// The paths of the tensors in ``parameters``, in the same order.
    var weightPaths: [TensorPath] {
        var paths: [TensorPath] = []
        var copy = self
        var visitor = TensorVisitor<Parameter, Device>(tensors: { tensor, role, path in
            if role == .weight, tensor.requiresGradient {
                paths.append(path)
            }
        })
        copy.visitTensors(&visitor)
        return paths
    }

    /// Replaces the trainable weights of the layer with the result of a closure.
    ///
    /// The closure receives the weights that require a gradient, in traversal order. Compute the gradients of
    /// these tensors and let an optimizer change them in place. When the closure returns, the visitor writes
    /// the tensors back to their positions, detaches them from the compute graph, and keeps them trainable.
    ///
    /// ```swift
    /// model.update { parameters in
    ///     optimizer.update(&parameters, along: loss.gradients(of: parameters))
    /// }
    /// ```
    ///
    /// - Parameter body: Closure that changes the weights. It must not add or remove tensors.
    mutating func update<Failure: Error>(_ body: (inout [Tensor<Parameter, Device>]) throws(Failure) -> Void) throws(Failure) {
        var parameters: [Tensor<Parameter, Device>] = []
        var collector = TensorVisitor<Parameter, Device>(tensors: { tensor, role, _ in
            if role == .weight, tensor.requiresGradient {
                parameters.append(tensor)
            }
        })
        visitTensors(&collector)
        let count = parameters.count

        try body(&parameters)
        precondition(parameters.count == count, "update(_:) received \(count) tensors, but returned \(parameters.count).")

        var index = 0
        var writer = TensorVisitor<Parameter, Device>(tensors: { tensor, role, _ in
            guard role == .weight, tensor.requiresGradient else {
                return
            }
            tensor = parameters[index]
            tensor.discardContext()
            tensor.requiresGradient = true
            index += 1
        })
        visitTensors(&writer)
    }

    /// Stops the training of all weights of the layer and its sublayers.
    ///
    /// A frozen weight does not require a gradient. The backward pass skips it, and ``update(_:)`` does not
    /// present it. Tensors that a layer reports with ``TensorVisitor/frozen(_:named:)-(Tensor<Element,Device>,_)`` are not changed.
    mutating func freeze() {
        setRequiresGradient(false)
    }

    /// Makes all weights of the layer and its sublayers trainable again.
    ///
    /// Tensors that a layer reports with ``TensorVisitor/frozen(_:named:)-(Tensor<Element,Device>,_)`` stay frozen.
    mutating func unfreeze() {
        setRequiresGradient(true)
    }

    /// Changes all layers of a type in the layer tree, including the layer itself.
    ///
    /// ```swift
    /// model.modifyLayers(of: Dropout<Float, CPU>.self) { dropout in
    ///     dropout.isActive = false
    /// }
    /// ```
    ///
    /// - Parameters:
    ///   - type: Type of the layers to change.
    ///   - body: Closure that changes one layer.
    mutating func modifyLayers<Layer: LayerType>(of type: Layer.Type, _ body: (inout Layer) -> Void) {
        if var layer = self as? Layer {
            body(&layer)
            // The cast to Layer succeeded, so Layer is Self and the cast back cannot fail.
            // swiftlint:disable:next force_cast
            self = layer as! Self
        }
        withoutActuallyEscaping(body) { body in
            var visitor = TensorVisitor<Parameter, Device>(tensors: { _, _, _ in }, layers: { erased, _ in
                guard var layer = erased as? Layer else {
                    return
                }
                body(&layer)
                erased = layer
            })
            visitTensors(&visitor)
        }
    }

    /// Returns all layers of a type in the layer tree, including the layer itself, in traversal order.
    /// - Parameter type: Type of the layers to return.
    /// - Returns: The layers of the type.
    func layers<Layer: LayerType>(of type: Layer.Type) -> [Layer] {
        var layers: [Layer] = []
        var copy = self
        copy.modifyLayers(of: type) { layer in
            layers.append(layer)
        }
        return layers
    }

    private mutating func setRequiresGradient(_ requiresGradient: Bool) {
        var visitor = TensorVisitor<Parameter, Device>(tensors: { tensor, role, _ in
            if role == .weight {
                tensor.requiresGradient = requiresGradient
            }
        })
        visitTensors(&visitor)
    }
}
