//
//  Layer.swift
//  DL4S
//
//  Created by Palle Klewitz on 12.10.19.
//  Copyright (c) 2019 - Palle Klewitz
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation

/// A layer of a neural network that performs an arbitrary transformation on its inputs to generate its outputs.
/// The layer may have parameters, which influence, how the outputs are generated.
public protocol LayerType<Inputs, Outputs, Parameter, Device>: Sendable {
    /// Inputs of the layer
    associatedtype Inputs
    
    /// Outputs of the layer
    associatedtype Outputs
    
    /// Element type of a parameter tensor
    associatedtype Parameter: NumericType
    
    /// Device type of a parameter tensor
    associatedtype Device: DeviceType
    
    /// Keypaths to parameters that influence the output of the layer.
    ///
    /// Use `parameterPaths(of: layerPath)` to concatenate while retaining `Sendable`.
    var parameterPaths: [WritableKeyPath<Self, Tensor<Parameter, Device>> & Sendable] { get }
    
    /// Parameters, that influence the output of the layer.
    var parameters: [Tensor<Parameter, Device>] { get }
    
    
    /// Performs a transformation determined by the type of the layer.
    ///
    /// The transformation may use parameters that the layer has.
    /// - Parameter inputs: Inputs of the layer
    /// - Returns: Outputs generated by transforming the inputs using the parameters of the layer.
    func callAsFunction(_ inputs: Inputs) -> Outputs
}

public extension LayerType {
    /// Returns the parameter key paths of a nested layer, prefixed with the key path to that layer.
    ///
    /// Use this to build `parameterPaths` for a layer that contains other layers.
    ///
    /// - Parameter layerPath: Key path from this layer to the nested layer.
    /// - Returns: One key path per parameter of the nested layer.
    func parameterPaths<Layer: LayerType>(of layerPath: WritableKeyPath<Self, Layer> & Sendable) -> [WritableKeyPath<Self, Tensor<Parameter, Device>> & Sendable] where Layer.Parameter == Parameter, Layer.Device == Device {
        self[keyPath: layerPath].parameterPaths.map { layerPath.appendingSendable(path: $0) }
    }
}

extension WritableKeyPath {
    /// Appends a key path and keeps the `Sendable` conformance.
    fileprivate func appendingSendable<AppendedValue>(path: WritableKeyPath<Value, AppendedValue> & Sendable) -> WritableKeyPath<Root, AppendedValue> & Sendable where Self: Sendable {
        let appended: WritableKeyPath<Root, AppendedValue> = appending(path: path as WritableKeyPath<Value, AppendedValue>)
        return unsafeBitCast(appended, to: (WritableKeyPath<Root, AppendedValue> & Sendable).self)
    }
}
